---
- name: create new bucket
  hosts: localhost
  connection: local

  tasks:
    - name: Creating a new bucket
      amazon.aws.s3_bucket:
        name: sanyarokinbucket
        state: present

- name: Create Build ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.nano
      ami: ami-00399ec92321828f5
      key_name: Ubuntu
      subnetid: subnet-48bd4b35
  
  tasks:
    - name: Add new security group
      ec2_group:
        name: "homework_lesson_13"
        description: "homework13 security group"
        region: "{{ region }}"
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # tomcat
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: test_firewall

    - name: Create build ec2 instance
      ec2:
         key_name: "{{ key_name }}"
         group: homework13  # security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 2
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group build
      add_host:
        hostname: "{{ ec2.instances[0].public_ip }}"
        groupname: build

    - name: Add new instance to host group prod
      add_host:
        hostname: "{{ ec2.instances[1].public_ip }}"
        groupname: prod

    - name: Wait for SSH to come
      wait_for: host={{ item.public_ip  }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ec2.instances}}"

- name: build war
  hosts: build
  become: yes
  connection: ssh
  remote_user: ubuntu
  vars_files:
    - variables.yml
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    ansible_ssh_private_key_file: ./Ubuntu.pem
 
  tasks:

    - name: Ensure openJDK is present
      apt:
        name: default-jdk
        update_cache: yes
        state: present

    - name: Ensure maven is present
      apt:
        name: maven
        state: present

    - name: Ensure pip is present
      apt:
        name: python3-pip
        state: present

    - name: Install boto
      pip:
        name: boto3

    - name: Enshure repo cloned
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/tmp/boxfuse-sample-java-war-hello
      tags: deploy

    - name: Enshure build war
      command: mvn package -f /tmp/boxfuse-sample-java-war-hello

    - name: Copy artefact to bucket
      amazon.aws.aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: sanyarokinbucket
        object: hello-1.0.war
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        mode: put

- name: deploy wer to prod
  hosts: prod
  become: yes
  connection: ssh
  remote_user: ubuntu
  vars_files:
    - variables.yml
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    ansible_ssh_private_key_file: ./Ubuntu.pem

  tasks:
    - name: Ensure Tomcat is present
      apt:
        name: tomcat9
        update_cache: yes
        state: present

    - name: Ensure tomcat service is running
      service:
        name: tomcat9
        state: started

    - name: Ensure pip is present
      apt:
        name: python3-pip
        state: present

    - name: Install boto
      pip:
        name: boto3

    - name: Download artefact to tomcat webroot
      amazon.aws.aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: sanyarokinbucket
        object: hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
        mode: get
